version: '3'

services:
    freeradius:
        build:
            context: .
            dockerfile: freeradius/Dockerfile 
        container_name: freeradius
        restart: unless-stopped
        depends_on:
          - mariadb
        networks:
          - radius

    routeros-6-48:
      image: evilfreelancer/docker-routeros:6.48.3
      container_name: chr-6.48.3
      restart: unless-stopped
      cap_add:
        - NET_ADMIN
      devices:
      - /dev/net/tun
      ports:
        - "22222:22"
        - "22223:23"
        - "28728:8728"
        - "28729:8729"
      networks:
        - radius

    mariadb:
      image: mariadb/server:10.5
      container_name: mariadb
      environment:
        - MYSQL_ROOT_PASSWORD=super 
        - MYSQL_USER=radtest
        - MYSQL_PASSWORD=radsecret
        - MYSQL_DATABASE=radius
      restart: unless-stopped
      volumes:
        - "./config/mysql/schema.sql:/docker-entrypoint-initdb.d/schema.sql"
      networks:
        - radius

networks:
  radius:
    ipam:
      config:
        - subnet: 10.0.0.0/24

